# Generated by Django 4.0.2 on 2022-04-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ticketDetail',
            fields=[
                ('ticketID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50)),
                ('trainID', models.IntegerField()),
                ('journeyDate', models.DateField()),
                ('totalFare', models.IntegerField(default=0)),
                ('seatNo', models.CharField(max_length=2)),
                ('passName', models.CharField(max_length=50)),
                ('passAge', models.IntegerField()),
                ('PassGender', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='trainDetails',
            fields=[
                ('trainID', models.AutoField(primary_key=True, serialize=False)),
                ('arrival', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('rent', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('bookedSeat', models.CharField(max_length=100)),
                ('time1', models.TimeField()),
                ('time2', models.TimeField()),
            ],
        ),
    ]
